- name: Enviar mensagem no Telegram
  hosts: localhost
  vars:
    telegram_bot_token: "7709438233:AAHhbzrkAUjxEJwCptMvuL3RyZSdZ8Vqw2Q"
    chat_id: "2018308195"
    message_text: "Mensagem de teste enviada via Ansible para o Telegram!"
  tasks:
    - name: Enviar mensagem para o chat
      uri:
        url: "https://api.telegram.org/bot{{ telegram_bot_token }}/sendMessage"
        method: POST
        headers:
          Content-Type: "application/json"
        body_format: raw
        body: "{{ {'chat_id': chat_id, 'text': message_text} | to_json }}"
        return_content: yes
